name: 'prova'
version: '1.0.0'
config-version: 2


profile: 'salesdbt'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
#docs-paths: ["docs"]


target-path: target
log-path: logs 


clean-targets:        
  - "target"
  - "dbt_packages"

# vars:


models:
  prova:
    staging:
      +materialized: view
    marts:
      +materialized: table


seeds:
  prova:
    csv_test:
      +schema: testing


snapshots: 
  prova:
    +target_database: postgres
    +target_schema: snapshotzim
    +unique_key: sk_target


tests:
  prova:
    +limit: 100
    +store_failures: true 
    +severity: error
    # database: postgres
    # schema: only_errors
    #where: