version: 2

seeds:
  - name: data
    description: static data from seed file
    config:
      enabled: true 
      #database: a
      schema: custom
      alias: data_alias
      # tests:
      #   - eita kkk
      # pre-hook: 
      # post-hook:

      # column_types:
      #   columna: 
      #   columnb:
      quote_columns: false
      fulll_refresh: false

      tags: ['seed']
      persist_docs: 
        columns: true 
        relation: true